USE skyx_user_db;
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE TABLE user;


CREATE TABLE `role` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(255) DEFAULT NULL,
  `UPDATED_DATE` datetime(6) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `status_master` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATUS` varchar(255) DEFAULT NULL,
  `UPDATED_DATE` datetime(6) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `EMAIL_ID` varchar(255) DEFAULT NULL,
  `PHONE_NO` varchar(255) DEFAULT NULL,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ROLE_ID` bigint(20) DEFAULT NULL,
  `STATUS_ID` bigint(20) DEFAULT NULL,
  `UPDATED_DATE` datetime(6) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK51nwvvirf4n67e3gdds36mbgq` (`ROLE_ID`),
  KEY `FK4ralcvc28jq1e5vnwkk3e00r9` (`STATUS_ID`),
  CONSTRAINT `FK4ralcvc28jq1e5vnwkk3e00r9` FOREIGN KEY (`STATUS_ID`) REFERENCES `status_master` (`ID`),
  CONSTRAINT `FK51nwvvirf4n67e3gdds36mbgq` FOREIGN KEY (`ROLE_ID`) REFERENCES `role` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `card` (
  `CARD_ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `CARD_OWNER_NAME` varchar(255) DEFAULT NULL,
  `CARD_NUMBER` bigint(20) DEFAULT NULL,
  `CARD_EXPIRY_MONTH` varchar(255) DEFAULT NULL,
  `CARD_EXPIRY_YEAR` varchar(255) DEFAULT NULL,
  `STATUS_ID` bigint(20) DEFAULT NULL,
  `USER_ID` bigint(20) DEFAULT NULL,
  `UPDATED_DATE` datetime(6) DEFAULT NULL,
  `CREATED_DATE` datetime(6) DEFAULT NULL,
  PRIMARY KEY (`CARD_ID`),
  KEY `FK3wqwtxt8aorwja1i33nvantk9` (`STATUS_ID`),
  KEY `FKdqh7bn08yyuas3l5qobb915k5` (`USER_ID`),
  CONSTRAINT `FK3wqwtxt8aorwja1i33nvantk9` FOREIGN KEY (`STATUS_ID`) REFERENCES `status_master` (`ID`),
  CONSTRAINT `FKdqh7bn08yyuas3l5qobb915k5` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


INSERT INTO skyx_user_db.status_master(ID,STATUS,UPDATED_DATE,CREATED_DATE) 
VALUES(1,"ACTIVE",NULL,NOW()),
(2,"BLOCKED",NULL,NOW()),
(3,"EXPIRED",NULL,NOW());

INSERT INTO skyx_user_db.role(ID,ROLE_NAME,UPDATED_DATE,CREATED_DATE) 
VALUES(1,"ADMIN",NULL,NOW()),
(2,"CUSTOMER",NULL,NOW()),
(3,"GUEST",NULL,NOW()),
(4,"STAFF",NULL,NOW()),
(5,"MANAGER",NULL,NOW());
